In [2]:
import numpy as np

In [6]:
## create array

arr1=np.array([1,2,3,4,5,6])
print (arr1)
type(arr1)
print(arr1.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
arr2= np.array([1,2,3,4,5,6])
## 1 row 6 column
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
arr2=np.array([[1, 2, 3, 4, 5, 6]])
arr2.shape

(1, 6)

In [ ]:
arr3=np.array([[1, 2, 3, 4, 5, 6],[6,7,8,5,3,3]])
print (arr3)
## 2 row 6 column

arr3.shape

[[1 2 3 4 5 6]
 [6 7 8 5 3 3]]


(2, 6)

In [17]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
##udentity

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##vectorized

arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,0])

##elememtal add

print("addition:", arr1+arr2)

####elememtal sub

print("sub:", arr2-arr1)



addition: [ 7  9 11 13  5]
sub: [ 5  5  5  5 -5]


In [ ]:
##universal

arr1

print(np.sqrt(arr1))

print(np.exp(arr1))

print(np.sin(arr1))

print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [29]:
##slicing and indexing

arr=np.array([[1,3,4], [5,7,3] , [ 7,  9 ,11]])
print("array: \n" ,arr)

## accessing element

arr[0][2]



array: 
 [[ 1  3  4]
 [ 5  7  3]
 [ 7  9 11]]


np.int64(4)

In [30]:
print(arr[1: ,3:])

[]


In [35]:
print(arr[1:,1:])

[[ 7  3]
 [ 9 11]]


In [37]:
arr[1:]=0
print(arr)

[[1 3 4]
 [0 0 0]
 [0 0 0]]


In [ ]:
##stasticalconcept and normalisation 

## mean 0 and sd of 1

""" .mean .var .std .median

and pass the list in thre . ()"""


In [39]:
## logical opration 

data = np.array([1,3,4,5,6,7,8,9])

data>5

data[data>5]

array([6, 7, 8, 9])